# Generated by Django 4.2.9 on 2024-02-18 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='handed_out',
        ),
    ]
