# Generated by Django 5.0.4 on 2024-05-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_radioaccessorytemplate_compatible_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtemplate',
            name='private',
            field=models.BooleanField(default=False, help_text='Whether this items are private and should not be issued via this system'),
        ),
    ]
