# Generated by Django 4.2.9 on 2024-02-18 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_item_handed_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembinding',
            name='item',
            field=models.OneToOneField(help_text='Item that is bound', on_delete=django.db.models.deletion.PROTECT, to='backend.item'),
        ),
    ]
