# Generated by Django 4.2.9 on 2024-03-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_itembinding_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlogentry',
            name='action',
            field=models.CharField(choices=[('USER_LOGIN', 'User logged in'), ('CREATE_ITEM_OWNER', 'Item owner created'), ('DELETE_ITEM_OWNER', 'Item owner deleted'), ('UPDATE_ITEM_OWNER', 'Item owner updated'), ('CREATE_ITEM', 'Item created'), ('DELETE_ITEM', 'Item deleted'), ('UPDATE_ITEM', 'Item updated'), ('CREATE_ITEM_TEMPLATE', 'Item template created'), ('DELETE_ITEM_TEMPLATE', 'Item template deleted'), ('UPDATE_ITEM_TEMPLATE', 'Item template updated'), ('CREATE_ITEM_BINDING', 'Item binding created'), ('DELETE_ITEM_BINDING', 'Item binding deleted'), ('UPDATE_ITEM_BINDING', 'Item binding updated'), ('CREATE_ORDER', 'Order created'), ('DELETE_ORDER', 'Order deleted'), ('UPDATE_ORDER', 'Order updated')], help_text='Action that was performed', max_length=64),
        ),
    ]
