# Generated by Django 4.2.9 on 2024-03-11 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_eventlogentry_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the order', max_length=128)),
                ('item', models.ForeignKey(blank=True, help_text='Exact Item that was ordered', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.item')),
                ('item_template', models.ForeignKey(blank=True, help_text='Exact Item template that was ordered', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.itemtemplate')),
                ('user', models.ForeignKey(help_text='User that should receive the item', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
