# Generated by Django 6.0.6 on 2026-06-13 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_itemtemplate_polymorphic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callbox',
            options={},
        ),
        migrations.AlterModelOptions(
            name='callboxtemplate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itemtemplate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pager',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pagertemplate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={},
        ),
        migrations.AlterModelOptions(
            name='phonetemplate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='radioaccessory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='radioaccessorytemplate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='radiodevice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='radiodevicetemplate',
            options={},
        ),
        migrations.AlterField(
            model_name='item',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template this item is based on', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.itemtemplate'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ef_reg_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the user in the EF reg database', null=True, unique=True),
        ),
    ]
