# Generated by Django 4.2.11 on 2024-04-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_radiocoding_radiodevicetemplate_coding'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('RadioDevice', 'Radio Device'), ('RadioAccessory', 'Radio Accessory'), ('Pager', 'Pager'), ('Phone', 'Phone'), ('Callbox', 'Callbox'), ('Other', 'Other')], default='Other', help_text='Type of the order', max_length=16),
            preserve_default=False,
        ),
    ]
