# Generated by Django 5.0.4 on 2024-04-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemowner',
            name='shortname',
            field=models.CharField(help_text='Short name of the owner', max_length=16, unique=True),
        ),
    ]
