# Generated by Django 5.0.4 on 2024-04-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_itemowner_shortname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlogentry',
            name='action',
            field=models.CharField(choices=[('USER_LOGIN', 'User logged in'), ('CREATE_ITEM_OWNER', 'Item owner created'), ('DELETE_ITEM_OWNER', 'Item owner deleted'), ('UPDATE_ITEM_OWNER', 'Item owner updated'), ('CREATE_ITEM', 'Item created'), ('DELETE_ITEM', 'Item deleted'), ('UPDATE_ITEM', 'Item updated'), ('CREATE_ITEM_TEMPLATE', 'Item template created'), ('DELETE_ITEM_TEMPLATE', 'Item template deleted'), ('UPDATE_ITEM_TEMPLATE', 'Item template updated'), ('CREATE_ITEM_BINDING', 'Item binding created'), ('DELETE_ITEM_BINDING', 'Item binding deleted'), ('UPDATE_ITEM_BINDING', 'Item binding updated'), ('CREATE_ORDER', 'Order created'), ('DELETE_ORDER', 'Order deleted'), ('UPDATE_ORDER', 'Order updated'), ('CREATE_RADIO_CODING', 'Radio coding created'), ('DELETE_RADIO_CODING', 'Radio coding deleted'), ('UPDATE_RADIO_CODING', 'Radio coding updated')], help_text='Action that was performed', max_length=64),
        ),
    ]
