# Generated by Django 5.0.4 on 2024-04-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_eventlogentry_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbox',
            name='camera_dhcp',
            field=models.BooleanField(blank=True, help_text='Whether the camera uses DHCP', null=True),
        ),
        migrations.AddField(
            model_name='callbox',
            name='camera_network',
            field=models.CharField(blank=True, choices=[('STAFF', 'Staff'), ('SECU', 'Security')], help_text='Network the camera is on', max_length=8, null=True),
        ),
    ]
