# Generated by Django 5.0.4 on 2024-04-24 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_itemcoordinates_item_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='itemcoordinates',
            name='item',
            field=models.OneToOneField(default='', help_text='Item this location is for', on_delete=django.db.models.deletion.CASCADE, to='backend.item'),
            preserve_default=False,
        ),
    ]
