# Generated by Django 5.0.4 on 2024-04-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_item_coordinates_itemcoordinates_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='UNSET', help_text='Nickname of the user', max_length=128),
            preserve_default=False,
        ),
    ]
